
project_id = "pueyxlqqmuupvlrzogfb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54324
max_header_length = 4096

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.strava-oauth]
verify_jwt = true

[functions.strava-callback]
verify_jwt = false

[functions.sync-strava-activities]
verify_jwt = true

[auth]
enabled = true
port = 54325
site_url = "https://pueyxlqqmuupvlrzogfb.supabase.co"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54326
inspector_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
