// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pueyxlqqmuupvlrzogfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1ZXl4bHFxbXV1cHZscnpvZ2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTE2MjYsImV4cCI6MjA2NTc2NzYyNn0.RrsU8DO3FxgRMKFLoBC3DXbSQ9bUIbzA2xA0kDR4wsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});